# Site settings
title: Nimish Verma
description: Personal website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nimish Verma
user_description: I am a final year B.Tech(Computer Science) student in Maharaja Agrasen Institute of Technology with strong interest in Data Science.
user_title: Full Stack Developer and Data Science Enthusiast
email: nimishverma@ymail.com
twitter_username: nimish7
github_username:  bigpythonimish
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-122693463-1"

exclude: ['package.json', 'src' , 'node_modules']
